name: CI

on: [push, pull_request]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Verify dockefiles are up-to-date
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          meson
        meson setup \
          --prefix=$(pwd)/_install \
          --wrap-mode=nofallback \
          -Dm4=enabled \
          -Dencoder=disabled \
          -Dstreamer=disabled \
          _build
        meson compile -C _build
        meson install -C _build
        git diff --exit-code

  rst-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          python3-pkg-resources \
          python3-restructuredtext-lint
    - run: rst-lint --level info .

  encoder-selfbuild-prodkmd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: docker build --file docker/encoder/ubuntu22.04/selfbuild-prodkmd/Dockerfile --tag cloud-encoder .

  encoder-intel-gfx:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: docker build --file docker/encoder/ubuntu22.04/intel-gfx/Dockerfile --tag cloud-encoder .

  streamer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: docker build --file docker/streamer/ubuntu22.04/Dockerfile --tag cloud-streamer .

  p2p:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: docker build --file docker/p2p/ubuntu22.04/Dockerfile --tag p2p .

  jstest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: docker build --file docker/jstest/ubuntu22.04/Dockerfile --tag jstest .

